name: ExampleApp-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Clone
      uses: actions/checkout@v2.4.0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: 5.0.x
    - name: Restore
      run: dotnet restore --verbosity minimal ./src/ExampleApp.csproj
    - name: Build
      run: dotnet build --no-restore --configuration Release --verbosity normal ./src/ExampleApp.csproj
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal ./src/ExampleApp.csproj
    - name: Publish
      run: dotnet publish --no-build --configuration Release --verbosity normal ./src/ExampleApp.csproj
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ExampleApp
        path: ./src/bin/Release/net5.0/publish
    - name: Login to DockerHub
      uses: docker/login-action@v1.14.1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.6.0
    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v2.9.0
      with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: feliperomero/exampleapp:dev